require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FactoriesController do

  def mock_factory(stubs={})
    @mock_factory ||= mock_model(Factory, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all factories as @factories" do
      Factory.stub(:all) { [mock_factory] }
      get :index
      assigns(:factories).should eq([mock_factory])
    end
  end

  describe "GET show" do
    it "assigns the requested factory as @factory" do
      Factory.stub(:find).with("37") { mock_factory }
      get :show, :id => "37"
      assigns(:factory).should be(mock_factory)
    end
  end

  describe "GET new" do
    it "assigns a new factory as @factory" do
      Factory.stub(:new) { mock_factory }
      get :new
      assigns(:factory).should be(mock_factory)
    end
  end

  describe "GET edit" do
    it "assigns the requested factory as @factory" do
      Factory.stub(:find).with("37") { mock_factory }
      get :edit, :id => "37"
      assigns(:factory).should be(mock_factory)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created factory as @factory" do
        Factory.stub(:new).with({'these' => 'params'}) { mock_factory(:save => true) }
        post :create, :factory => {'these' => 'params'}
        assigns(:factory).should be(mock_factory)
      end

      it "redirects to the created factory" do
        Factory.stub(:new) { mock_factory(:save => true) }
        post :create, :factory => {}
        response.should redirect_to(factory_url(mock_factory))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved factory as @factory" do
        Factory.stub(:new).with({'these' => 'params'}) { mock_factory(:save => false) }
        post :create, :factory => {'these' => 'params'}
        assigns(:factory).should be(mock_factory)
      end

      it "re-renders the 'new' template" do
        Factory.stub(:new) { mock_factory(:save => false) }
        post :create, :factory => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested factory" do
        Factory.stub(:find).with("37") { mock_factory }
        mock_factory.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :factory => {'these' => 'params'}
      end

      it "assigns the requested factory as @factory" do
        Factory.stub(:find) { mock_factory(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:factory).should be(mock_factory)
      end

      it "redirects to the factory" do
        Factory.stub(:find) { mock_factory(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(factory_url(mock_factory))
      end
    end

    describe "with invalid params" do
      it "assigns the factory as @factory" do
        Factory.stub(:find) { mock_factory(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:factory).should be(mock_factory)
      end

      it "re-renders the 'edit' template" do
        Factory.stub(:find) { mock_factory(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested factory" do
      Factory.stub(:find).with("37") { mock_factory }
      mock_factory.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the factories list" do
      Factory.stub(:find) { mock_factory }
      delete :destroy, :id => "1"
      response.should redirect_to(factories_url)
    end
  end

end
